import fs from "node:fs/promises";

import { describe, expect, it } from "vitest";

import { runConfig } from "../../src/config/command.js";
import { runInit } from "../../src/init/init.js";
import { TRUTHMARK_VERSION } from "../../src/version.js";
import { createTempRepo } from "../helpers/temp-repo.js";

describe("runInit instruction integration", () => {
  it("installs a single managed AGENTS block with agent-native workflow guidance", async () => {
    const repo = await createTempRepo();

    try {
      await runConfig(repo.rootDir, {});
      await runInit(repo.rootDir);

      const agents = await repo.readFile("AGENTS.md");

      expect(agents.match(/<!-- truthmark:start -->/g)).toHaveLength(1);
      expect(agents.match(/<!-- truthmark:end -->/g)).toHaveLength(1);
      expect(agents.split("\n").length).toBeLessThanOrEqual(25);
      expect(agents.slice(0, 220)).toContain("Truthmark Workflow");
      expect(agents).toContain("/skill truthmark-sync");
      expect(agents).toContain(`Generated by Truthmark ${TRUTHMARK_VERSION}`);
      expect(agents).toContain("Sync: finish-time when functional code changed");
      expect(agents).toContain("code changed -> tests -> Sync -> report");
      expect(agents).toContain("Delegation is host-owned");
      expect(agents).toContain(
        "Explicit workflows: Truth Structure, Truth Realize, Truth Check",
      );
      expect(agents).toContain("load the installed skill for details");
      expect(agents).not.toContain("/skill truthmark-structure");
      expect(agents).not.toContain("/skill truthmark-check");
      expect(agents).not.toContain(
        "truthmark check --json --workflow truth-sync",
      );
      expect(agents).not.toContain("Truth Structure: completed");
      expect(agents).not.toContain("Truth Sync: completed");
      expect(agents).not.toContain("Truth Sync: skipped");
      expect(agents).not.toContain("Truth Realize: completed");
      expect(agents).not.toContain("### Truth Check");
      expect(agents).toContain("inspect checkout directly");
      expect(agents).not.toContain("truthmark packet --changed");

      await expect(fs.stat(`${repo.rootDir}/OPENCODE.md`)).rejects.toThrow();
    } finally {
      await repo.cleanup();
    }
  });

  it("rerenders the managed block without duplicating it and leaves subagent choice to the host", async () => {
    const repo = await createTempRepo();

    try {
      await runConfig(repo.rootDir, {});
      await runInit(repo.rootDir);
      await repo.writeFile(
        ".truthmark/config.yml",
        `version: 1
authority:
  - TRUTHMARK.md
  - docs/truthmark/areas.md
  - docs/truthmark/areas/**/*.md
instruction_targets:
  - AGENTS.md
frontmatter:
  required: []
  recommended:
    - status
ignore: []
realization:
  enabled: true
`,
      );

      await runInit(repo.rootDir);

      const agents = await repo.readFile("AGENTS.md");

      expect(agents.match(/<!-- truthmark:start -->/g)).toHaveLength(1);
      expect(agents).toContain("Delegation is host-owned");
      expect(agents).not.toContain(".truthmark/local.yml");
      expect(agents).not.toContain("truth_sync.sync_agent");
      expect(agents).toContain("later functional changes reopen the gate");
    } finally {
      await repo.cleanup();
    }
  });
});
