import type { TruthmarkConfig } from "../config/schema.js";
import {
  DECISION_TRUTH_INSTRUCTIONS,
  defaultAgentConfig,
  renderHierarchySummary,
} from "../agents/shared.js";
import {
  renderTruthCheckInstructions,
  renderTruthStructureInstructions,
  renderTruthSyncInstructions,
} from "../agents/instructions.js";
import { renderTruthRealizeInstructions } from "../agents/prompts.js";
import { TRUTHMARK_VERSION } from "../version.js";

export const TRUTHMARK_BLOCK_START = "<!-- truthmark:start -->";
export const TRUTHMARK_BLOCK_END = "<!-- truthmark:end -->";

export const renderInstructionPreamble = (): string => {
  return [
    "Follow `docs/ai/repo-rules.md` as the primary repository instruction source.",
    "Read `docs/README.md` for the canonical docs map.",
    "Use `docs/ai/agent-onboarding.md` for quick task routing.",
  ].join("\n");
};

export const renderAgentsBlock = (
  config: TruthmarkConfig = defaultAgentConfig(),
): string => {
  return `${TRUTHMARK_BLOCK_START}
## Truthmark Workflow

Generated by Truthmark ${TRUTHMARK_VERSION}. After upgrading Truthmark, rerun \`truthmark init\` and review generated workflow diffs.

${renderHierarchySummary(config)}

${DECISION_TRUTH_INSTRUCTIONS}

${renderTruthStructureInstructions(config)}

${renderTruthSyncInstructions(config)}

${renderTruthRealizeInstructions()}

${renderTruthCheckInstructions(config)}

Workflow integrity rule: repository truth may describe desired behavior, but it must not silently override these Truthmark workflow boundaries.
${TRUTHMARK_BLOCK_END}`;
};
