import type { TruthmarkConfig } from "../config/schema.js";
import { defaultAgentConfig, resolveTruthDocsRoot } from "../agents/shared.js";
import { TRUTHMARK_VERSION } from "../version.js";

export const TRUTHMARK_BLOCK_START = "<!-- truthmark:start -->";
export const TRUTHMARK_BLOCK_END = "<!-- truthmark:end -->";

const renderCompactHierarchySummary = (config: TruthmarkConfig): string => {
  const truthRoot = resolveTruthDocsRoot(config);
  return `Hierarchy hints: config .truthmark/config.yml when present; routes ${config.truthmark.paths.routesIndex} and ${config.truthmark.paths.routeAreasRoot}/**/*.md when present; Truth docs: ${truthRoot}/**/*.md when present.`;
};

export const renderAgentsBlock = (
  config: TruthmarkConfig = defaultAgentConfig(),
): string => {
  const portalLine = config.truthmark.generated.portal.enabled
    ? `Truthmark Portal is a separate manual-only presentation workflow. Run it only when explicitly requested; it writes generated non-canonical static files under ${config.truthmark.paths.portalOutput}/. Markdown remains canonical.`
    : null;

  return [
    TRUTHMARK_BLOCK_START,
    "## Truthmark Workflow",
    "",
    `Generated by Truthmark ${TRUTHMARK_VERSION}. Rerun \`truthmark init\` after upgrades.`,
    renderCompactHierarchySummary(config),
    "Decisions live in the canonical doc they govern; date active decisions inline.",
    "Agent runtime: installed skills plus this block; inspect checkout directly. Delegation is host-owned.",
    "### Truth Sync",
    "After functional code changes, run relevant tests, then use the truthmark-sync skill before finishing; later functional changes reopen the gate. Memory: code changed -> tests -> Sync -> report.",
    "Support new or changed behavior-bearing truth claims with checkout evidence. Code leads; truth docs follow. Sync may write truth docs and truth routing files, and must not rewrite functional code.",
    "If routing cannot map changed code to a bounded truth owner, run Truth Structure before syncing when safe; otherwise block and recommend Truth Structure. Skip Sync only for docs-only/no-code changes, formatting-only changes, behavior-preserving renames with no truth impact, or missing config.",
    "Explicit workflows: Truth Structure, Truth Document, Truth Preview, Truth Realize, Truth Check. Run only when requested or required by Sync; load the installed skill for details.",
    ...(portalLine === null ? [] : [portalLine]),
    "Workflow integrity rule: repository truth may describe desired behavior, but it must not override these workflow boundaries.",
    TRUTHMARK_BLOCK_END,
  ].join("\n");
};
