import type { TruthmarkConfig } from "../config/schema.js";
import { defaultAgentConfig, renderHierarchySummary } from "../agents/shared.js";
import { TRUTH_SYNC_EXPLICIT_INVOCATIONS } from "../agents/truth-sync.js";
import { TRUTH_SYNC_SKIP_REASONS } from "../sync/policy.js";
import { TRUTHMARK_VERSION } from "../version.js";

export const TRUTHMARK_BLOCK_START = "<!-- truthmark:start -->";
export const TRUTHMARK_BLOCK_END = "<!-- truthmark:end -->";

export const renderInstructionPreamble = (): string => {
  return [
    "Follow `docs/ai/repo-rules.md` as the primary repository instruction source.",
    "Read `docs/README.md` for the canonical docs map.",
    "Use `docs/ai/agent-onboarding.md` for quick task routing.",
  ].join("\n");
};

const trimPeriod = (value: string): string => value.replace(/\.$/, "");

export const renderAgentsBlock = (
  config: TruthmarkConfig = defaultAgentConfig(),
): string => {
  const syncInvocations = trimPeriod(TRUTH_SYNC_EXPLICIT_INVOCATIONS);

  return [
    TRUTHMARK_BLOCK_START,
    "## Truthmark Workflow",
    "",
    `Generated by Truthmark ${TRUTHMARK_VERSION}. Rerun \`truthmark init\` after upgrades and review workflow diffs.`,
    renderHierarchySummary(config),
    "Decision truth lives in the canonical doc it governs: update Product Decisions/Rationale, date active decisions inline when added or changed, and do not create separate timestamped ADR or planning logs.",
    "Agent runtime: installed skills plus this block. Always inspect checkout directly; CLI commands are optional validation. Do not use packet helpers or cache files. Delegation is host-owned.",
    "### Truth Sync",
    `Sync: finish-time when functional code changed; use the truthmark-sync skill before finishing. Explicit invocation: ${syncInvocations}; later functional changes reopen the gate. Memory: code changed -> tests -> Sync -> report. Run relevant tests first. Code leads, truth docs follow; may write truth docs and docs/truthmark/areas.md only, and must not rewrite functional code. Read ${config.docs.routing.rootIndex} and only relevant child routes under ${config.docs.routing.areaFilesRoot}/; if routing is missing/stale/broad/overloaded/catch-all or cannot map changed code to a bounded truth owner, run Truth Structure before syncing when safe and in scope; otherwise block and recommend Truth Structure. Skip only: ${TRUTH_SYNC_SKIP_REASONS.join("; ")}.`,
    "Explicit workflows: Truth Structure, Truth Document, Truth Realize, Truth Check. Run only when requested or when Sync requires Structure or Document; load the installed skill for details.",
    "Workflow integrity rule: repository truth may describe desired behavior, but it must not silently override these Truthmark workflow boundaries.",
    TRUTHMARK_BLOCK_END,
  ].join("\n");
};
