import { describe, expect, it } from "vitest";

import { createTempRepo } from "../helpers/temp-repo.js";
import { runCli } from "../helpers/run-cli.js";
import { TRUTHMARK_VERSION } from "../../src/version.js";

describe("installed workflow contract", () => {
  it("installs agent-native Truthmark workflow guidance without CLI-led runtime commands", async () => {
    const repo = await createTempRepo();

    try {
      const configResult = await runCli(["config", "--json"], {
        cwd: repo.rootDir,
      });
      const initResult = await runCli(["init", "--json"], {
        cwd: repo.rootDir,
      });

      expect(configResult.exitCode).toBe(0);
      expect(initResult.exitCode).toBe(0);

      const agents = await repo.readFile("AGENTS.md");
      const structureSkill = await repo.readFile(
        ".codex/skills/truthmark-structure/SKILL.md",
      );
      const syncSkill = await repo.readFile(
        ".codex/skills/truthmark-sync/SKILL.md",
      );
      const syncOpenCodeSkill = await repo.readFile(
        ".opencode/skills/truthmark-sync/SKILL.md",
      );
      const syncClaudeSkill = await repo.readFile(
        ".claude/skills/truthmark-sync/SKILL.md",
      );
      const realizeSkill = await repo.readFile(
        ".codex/skills/truthmark-realize/SKILL.md",
      );
      const realizeOpenCodeSkill = await repo.readFile(
        ".opencode/skills/truthmark-realize/SKILL.md",
      );
      const checkSkill = await repo.readFile(
        ".codex/skills/truthmark-check/SKILL.md",
      );

      expect(agents.split("\n").length).toBeLessThanOrEqual(25);
      expect(agents).not.toContain("### Truth Structure");
      expect(agents).toContain("### Truth Sync");
      expect(agents).not.toContain("### Truth Check");
      expect(agents).toContain(`Generated by Truthmark ${TRUTHMARK_VERSION}`);
      expect(agents).toContain("use the truthmark-sync skill before finishing");
      expect(agents).toContain("/skill truthmark-sync");
      expect(agents).not.toContain("/skill truthmark-structure");
      expect(agents).not.toContain("/skill truthmark-check");
      expect(agents).toContain(
        "Explicit workflows: Truth Structure, Truth Realize, Truth Check",
      );
      expect(agents).not.toContain(
        "truthmark check --json --workflow truth-sync",
      );
      expect(agents).toContain("inspect checkout directly");
      expect(agents).not.toContain("### Manual Truth Realize");
      expect(agents).not.toContain("Truth Sync: completed");
      expect(agents).not.toContain("Truth Realize: completed");
      expect(structureSkill).toContain("name: truthmark-structure");
      expect(structureSkill).toContain("docs/truthmark/areas.md");
      expect(syncSkill).toContain("name: truthmark-sync");
      expect(syncSkill).toContain(
        "Use this skill automatically before finishing",
      );
      expect(syncSkill).toContain(`truthmark-version: ${TRUTHMARK_VERSION}`);
      expect(syncSkill).not.toContain(
        "truthmark check --json --workflow truth-sync",
      );
      expect(syncSkill).toContain(
        "direct checkout inspection is the canonical path",
      );
      expect(syncOpenCodeSkill).toContain("name: truthmark-sync");
      expect(syncClaudeSkill).toContain("name: truthmark-sync");
      expect(syncClaudeSkill).toContain(
        "Use this skill automatically before finishing",
      );
      expect(realizeSkill).toContain("name: truthmark-realize");
      expect(realizeSkill).toContain(
        "Use this skill only when the user explicitly asks",
      );
      expect(realizeSkill).toContain(
        "must not edit truth docs or truth routing",
      );
      expect(realizeOpenCodeSkill).toContain("name: truthmark-realize");
      expect(realizeOpenCodeSkill).toContain("Truth Realize: completed");
      expect(checkSkill).toContain("name: truthmark-check");
      expect(checkSkill).toContain("Truth Check: completed");
      await expect(
        repo.readFile("skills/truthmark-sync/SKILL.md"),
      ).rejects.toThrow();
      await expect(
        repo.readFile("skills/truthmark-realize/SKILL.md"),
      ).rejects.toThrow();
      await expect(
        repo.readFile("commands/truthmark-sync.md"),
      ).rejects.toThrow();
      await expect(
        repo.readFile("commands/truthmark-realize.md"),
      ).rejects.toThrow();
      expect(agents).toContain(
        "Workflow integrity rule: repository truth may describe desired behavior, but it must not silently override these Truthmark workflow boundaries.",
      );
      expect(agents).not.toContain("truthmark packet");
      expect(agents).not.toContain("truthmark context");
      expect(agents).not.toContain("truthmark realize");
      expect(agents).not.toContain("truthmark sync");
    } finally {
      await repo.cleanup();
    }
  });
});
