import fs from "node:fs/promises";
import { createHash } from "node:crypto";

import type { TruthmarkConfig } from "../config/schema.js";
import { resolveRepoPath } from "../fs/paths.js";
import type { Diagnostic } from "../output/diagnostic.js";
import { TRUTHMARK_BLOCK_END, TRUTHMARK_BLOCK_START } from "../templates/agents-block.js";
import { renderGeneratedSurfaces } from "../templates/generated-surfaces.js";
import { TRUTHMARK_VERSION } from "../version.js";

const readOptionalFile = async (rootDir: string, filePath: string): Promise<string | null> => {
  try {
    return await fs.readFile(resolveRepoPath(rootDir, filePath), "utf8");
  } catch (error: unknown) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return null;
    }

    throw error;
  }
};

const extractManagedBlock = (content: string): string | null => {
  const startIndex = content.indexOf(TRUTHMARK_BLOCK_START);
  const endIndex = content.indexOf(TRUTHMARK_BLOCK_END);

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    return null;
  }

  return content.slice(startIndex, endIndex + TRUTHMARK_BLOCK_END.length);
};

const normalizeGeneratedSurfaceContent = (content: string | null): string | null => {
  if (content === null) {
    return null;
  }

  return content.replace(/\r\n/g, "\n").replace(/\n$/u, "");
};

const sha256 = (content: string): string =>
  createHash("sha256").update(content).digest("hex");

const fullWorkflowBodyMarkers = [
  "Parent workflow:",
  "Evidence checklist:",
  "Report completion in this shape:",
];

const adapterCanonicalReferences = (content: string): string[] => {
  return Array.from(
    content.matchAll(/\.truthmark\/agent\/[^\s)]+/gu),
    (match) => match[0].replace(/[",.;:]$/u, ""),
  );
};

const adapterMode = (content: string): "adapter" | "expanded-adapter" | null => {
  if (content.includes("<!-- truthmark:adapter-mode=expanded-adapter -->")) {
    return "expanded-adapter";
  }

  if (
    content.includes("not the workflow source of truth") ||
    content.includes("not source of truth")
  ) {
    return "adapter";
  }

  return null;
};

const expandedCanonicalPath = (content: string): string | null =>
  content.match(/truthmark:canonical=([^\s]+)\s*-->/u)?.[1] ?? null;

const expandedCanonicalHash = (content: string): string | null =>
  content.match(/truthmark:canonical-sha256=([a-f0-9]+)\s*-->/u)?.[1] ?? null;

const versionMarkers = (content: string): string[] => {
  const markers: string[] = [];
  const patterns = [
    /truthmark-version:\s*([^\s]+)/gu,
    /Generated by Truthmark\s+([^\s.]+(?:\.[^\s.]+){1,2})/gu,
    /^version:\s*"(\d+\.\d+\.\d+)"\s*$/gmu,
  ];

  for (const pattern of patterns) {
    for (const match of content.matchAll(pattern)) {
      if (match[1]) {
        markers.push(match[1]);
      }
    }
  }

  return markers;
};

export const checkGeneratedSurfaces = async (
  rootDir: string,
  config: TruthmarkConfig,
): Promise<Diagnostic[]> => {
  const diagnostics: Diagnostic[] = [];

  for (const surface of renderGeneratedSurfaces(config)) {
    const content = await readOptionalFile(rootDir, surface.path);

    if (content === null) {
      diagnostics.push({
        category: "generated-surface",
        severity: "review",
        message: `Generated surface ${surface.path} is missing; rerun truthmark init.`,
        file: surface.path,
      });
      continue;
    }

    const mode = adapterMode(content);
    if (mode === "adapter") {
      const duplicatedMarker = fullWorkflowBodyMarkers.find((marker) =>
        content.includes(marker),
      );

      if (duplicatedMarker !== undefined) {
        diagnostics.push({
          category: "generated-surface",
          severity: "review",
          message: `Generated adapter ${surface.path} duplicates workflow body marker "${duplicatedMarker}"; rerun truthmark init.`,
          file: surface.path,
        });
      }
    }

    if (mode !== null) {
      for (const canonicalReference of adapterCanonicalReferences(content)) {
        if ((await readOptionalFile(rootDir, canonicalReference)) === null) {
          diagnostics.push({
            category: "generated-surface",
            severity: "review",
            message: `Generated adapter ${surface.path} references missing canonical package file ${canonicalReference}; rerun truthmark init.`,
            file: surface.path,
          });
        }
      }
    }

    if (mode === "expanded-adapter") {
      const canonicalPath = expandedCanonicalPath(content);
      const recordedHash = expandedCanonicalHash(content);
      const canonicalContent =
        canonicalPath === null ? null : await readOptionalFile(rootDir, canonicalPath);

      if (
        canonicalPath !== null &&
        recordedHash !== null &&
        canonicalContent !== null &&
        sha256(`${canonicalPath}\n${canonicalContent}`) !== recordedHash
      ) {
        diagnostics.push({
          category: "generated-surface",
          severity: "review",
          message: `Generated expanded adapter ${surface.path} has stale canonical hash for ${canonicalPath}; rerun truthmark init.`,
          file: surface.path,
        });
      }
    }

    const comparableContent = normalizeGeneratedSurfaceContent(
      surface.managedBlock ? extractManagedBlock(content) : content,
    );
    const expectedContent = normalizeGeneratedSurfaceContent(surface.content);

    if (comparableContent !== expectedContent) {
      diagnostics.push({
        category: "generated-surface",
        severity: "review",
        message: `Generated surface ${surface.path} is stale; rerun truthmark init.`,
        file: surface.path,
      });
    }

    const versionContent = surface.managedBlock ? comparableContent ?? "" : content;
    const mismatchedVersions = versionMarkers(versionContent).filter(
      (version) => version !== TRUTHMARK_VERSION,
    );

    if (mismatchedVersions.length > 0) {
      diagnostics.push({
        category: "generated-surface",
        severity: "review",
        message: `Generated surface ${surface.path} has Truthmark version ${mismatchedVersions[0]} but current version is ${TRUTHMARK_VERSION}; rerun truthmark init.`,
        file: surface.path,
      });
    }
  }

  return diagnostics;
};
