export const VALIDATE_SYNC_REPORT_SCRIPT = String.raw`#!/usr/bin/env node
// Generated by Truthmark. Rerun truthmark init after upgrades.
import fs from "node:fs";
import process from "node:process";

const helper = "validate-sync-report";

const print = (payload) => {
  process.stdout.write(JSON.stringify(payload, null, 2) + "\n");
};

const fail = (errors) => {
  print({ ok: false, helper, errors });
  process.exit(1);
};

const args = process.argv.slice(2);
if (args.length !== 1) {
  fail(["expected exactly one report file argument"]);
}

let text = "";
try {
  text = fs.readFileSync(args[0], "utf8");
} catch (error) {
  fail(["could not read report file: " + error.message]);
}

const statusMatch = text.match(/^\s*Truth Sync:\s*(completed|blocked|skipped)\b/im);
if (statusMatch === null) {
  fail(["missing Truth Sync status: expected completed, blocked, or skipped"]);
}

const checks = ["status: " + statusMatch[1].toLowerCase()];
const errors = [];

const escapeRegex = (value) =>
  value.split("").map((char) => ".+*?^$()[]{}|\\\\".includes(char) ? "\\\\" + char : char).join("");

const hasLabel = (label) => {
  const escaped = escapeRegex(label);
  return new RegExp("(^|\\n)\\s*(?:#{1,6}\\s*)?" + escaped + "\\s*:?\\s*(\\n|$)", "iu").test(text);
};

const getSection = (label) => {
  const lines = text.split(/\r?\n/);
  const labelPattern = new RegExp("^(?:#{1,6}\\s*)?" + escapeRegex(label) + "\\s*:?\\s*$", "iu");
  const sectionHeaderPattern = /^(?:#{1,6}\s*)?[A-Z][A-Za-z0-9 ]+:\s*$/u;
  const startIndex = lines.findIndex((line) => labelPattern.test(line));

  if (startIndex === -1) {
    return null;
  }

  const nextSectionOffset = lines.slice(startIndex + 1).findIndex((line) => sectionHeaderPattern.test(line));
  const endIndex = nextSectionOffset === -1 ? lines.length : startIndex + 1 + nextSectionOffset;

  return lines.slice(startIndex + 1, endIndex).join("\n").trim();
};

const validateEvidenceChecked = () => {
  const section = getSection("Evidence checked");

  if (section === null || section === "") {
    errors.push("Evidence checked must include at least one structured entry");
    return;
  }

  const entries = section.split(/\n(?=-\s+)/u).map((entry) => entry.trim()).filter(Boolean);

  if (entries.length === 0) {
    errors.push("Evidence checked must include at least one structured entry");
    return;
  }

  const entryPattern = /^- Claim:\s*\S[^\n]*\n {2,}Evidence:\s*\S[^\n]*\n {2,}Result:\s*(supported|narrowed|removed|blocked)\s*$/iu;
  for (const [index, entry] of entries.entries()) {
    if (!entryPattern.test(entry)) {
      errors.push(
        "Evidence checked entry " +
          (index + 1) +
          " must match '- Claim: ...' followed by indented 'Evidence: ...' and 'Result: supported | narrowed | removed | blocked'",
      );
    }
  }

  if (errors.length === 0) {
    checks.push("Evidence checked entries include Claim:, Evidence:, and Result: supported | narrowed | removed | blocked");
  }
};

const validateHelperScripts = (requiredHelpers) => {
  const section = getSection("Helper scripts");

  if (section === null || section === "") {
    errors.push("Helper scripts must include status for package helpers");
    return;
  }

  const entries = section.split(/\n/u).map((entry) => entry.trim()).filter(Boolean);
  const statusPattern = /^-\s*([a-z0-9-]+):\s*(?:ran,\s*(?:passed|failed)|skipped,\s*\S.*)$/iu;

  for (const entry of entries) {
    if (!statusPattern.test(entry)) {
      errors.push("Helper scripts entries must match '- helper-id: ran, passed' or '- helper-id: skipped, reason'");
    }
  }

  for (const helperId of requiredHelpers) {
    if (!entries.some((entry) => entry.toLowerCase().startsWith("- " + helperId + ":"))) {
      errors.push("missing Helper scripts status: " + helperId);
    }
  }

  if (errors.length === 0) {
    checks.push("Helper scripts statuses include " + requiredHelpers.join(", "));
  }
};

if (statusMatch[1].toLowerCase() === "completed") {
  for (const label of [
    "Changed code reviewed",
    "Ownership reviewed",
    "Truth docs updated",
    "Evidence checked",
    "Helper scripts",
    "Notes",
  ]) {
    if (hasLabel(label)) {
      checks.push(label);
    } else {
      errors.push("missing required section: " + label);
    }
  }

  validateEvidenceChecked();
  validateHelperScripts(["validate-sync-report", "validate-write-lease"]);
}

if (errors.length > 0) {
  fail(errors);
}

print({ ok: true, helper, checks });
`;

export const VALIDATE_DOCUMENT_REPORT_SCRIPT = String.raw`#!/usr/bin/env node
// Generated by Truthmark. Rerun truthmark init after upgrades.
import fs from "node:fs";
import process from "node:process";

const helper = "validate-document-report";

const print = (payload) => {
  process.stdout.write(JSON.stringify(payload, null, 2) + "\n");
};

const fail = (errors) => {
  print({ ok: false, helper, errors });
  process.exit(1);
};

const args = process.argv.slice(2);
if (args.length !== 1) {
  fail(["expected exactly one report file argument"]);
}

let text = "";
try {
  text = fs.readFileSync(args[0], "utf8");
} catch (error) {
  fail(["could not read report file: " + error.message]);
}

const statusMatch = text.match(/^\s*Truth Document:\s*(completed|blocked)\b/im);
if (statusMatch === null) {
  fail(["missing Truth Document status: expected completed or blocked"]);
}

const checks = ["status: " + statusMatch[1].toLowerCase()];
const errors = [];

const escapeRegex = (value) =>
  value.split("").map((char) => ".+*?^$()[]{}|\\\\".includes(char) ? "\\\\" + char : char).join("");

const hasLabel = (label) => {
  const escaped = escapeRegex(label);
  return new RegExp("(^|\\n)\\s*(?:#{1,6}\\s*)?" + escaped + "\\s*:?\\s*(\\n|$)", "iu").test(text);
};

const getSection = (label) => {
  const lines = text.split(/\r?\n/);
  const labelPattern = new RegExp("^(?:#{1,6}\\s*)?" + escapeRegex(label) + "\\s*:?\\s*$", "iu");
  const sectionHeaderPattern = /^(?:#{1,6}\s*)?[A-Z][A-Za-z0-9 ]+:\s*$/u;
  const startIndex = lines.findIndex((line) => labelPattern.test(line));

  if (startIndex === -1) {
    return null;
  }

  const nextSectionOffset = lines.slice(startIndex + 1).findIndex((line) => sectionHeaderPattern.test(line));
  const endIndex = nextSectionOffset === -1 ? lines.length : startIndex + 1 + nextSectionOffset;

  return lines.slice(startIndex + 1, endIndex).join("\n").trim();
};

const validateEvidenceChecked = () => {
  const section = getSection("Evidence checked");

  if (section === null || section === "") {
    errors.push("Evidence checked must include at least one structured entry");
    return;
  }

  const entries = section.split(/\n(?=-\s+)/u).map((entry) => entry.trim()).filter(Boolean);

  if (entries.length === 0) {
    errors.push("Evidence checked must include at least one structured entry");
    return;
  }

  const entryPattern = /^- Claim:\s*\S[^\n]*\n {2,}Evidence:\s*\S[^\n]*\n {2,}Result:\s*(supported|narrowed|removed|blocked)\s*$/iu;
  for (const [index, entry] of entries.entries()) {
    if (!entryPattern.test(entry)) {
      errors.push(
        "Evidence checked entry " +
          (index + 1) +
          " must match '- Claim: ...' followed by indented 'Evidence: ...' and 'Result: supported | narrowed | removed | blocked'",
      );
    }
  }

  if (errors.length === 0) {
    checks.push("Evidence checked entries include Claim:, Evidence:, and Result: supported | narrowed | removed | blocked");
  }
};

const validateHelperScripts = (requiredHelpers) => {
  const section = getSection("Helper scripts");

  if (section === null || section === "") {
    errors.push("Helper scripts must include status for package helpers");
    return;
  }

  const entries = section.split(/\n/u).map((entry) => entry.trim()).filter(Boolean);
  const statusPattern = /^-\s*([a-z0-9-]+):\s*(?:ran,\s*(?:passed|failed)|skipped,\s*\S.*)$/iu;

  for (const entry of entries) {
    if (!statusPattern.test(entry)) {
      errors.push("Helper scripts entries must match '- helper-id: ran, passed' or '- helper-id: skipped, reason'");
    }
  }

  for (const helperId of requiredHelpers) {
    if (!entries.some((entry) => entry.toLowerCase().startsWith("- " + helperId + ":"))) {
      errors.push("missing Helper scripts status: " + helperId);
    }
  }

  if (errors.length === 0) {
    checks.push("Helper scripts statuses include " + requiredHelpers.join(", "));
  }
};

if (statusMatch[1].toLowerCase() === "completed") {
  for (const label of [
    "Implementation reviewed",
    "Ownership reviewed",
    "Evidence checked",
    "Helper scripts",
    "Notes",
  ]) {
    if (hasLabel(label)) {
      checks.push(label);
    } else {
      errors.push("missing required section: " + label);
    }
  }

  if (hasLabel("Truth docs updated") || hasLabel("Truth docs created")) {
    checks.push("Truth docs updated or created");
  } else {
    errors.push("missing required section: Truth docs updated or Truth docs created");
  }

  validateEvidenceChecked();
  validateHelperScripts(["validate-document-report", "validate-write-lease"]);
}

if (errors.length > 0) {
  fail(errors);
}

print({ ok: true, helper, checks });
`;

export const VALIDATE_WRITE_LEASE_SCRIPT = String.raw`#!/usr/bin/env node
// Generated by Truthmark. Rerun truthmark init after upgrades.
import fs from "node:fs";
import process from "node:process";

const helper = "validate-write-lease";

const print = (payload) => {
  process.stdout.write(JSON.stringify(payload, null, 2) + "\n");
};

const fail = (errors) => {
  print({ ok: false, helper, errors });
  process.exit(1);
};

const args = process.argv.slice(2);
if (args.length !== 2) {
  fail(["expected lease/report file and changed-files file arguments"]);
}

const readText = (filePath, label) => {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch (error) {
    fail(["could not read " + label + ": " + error.message]);
  }
};

const normalizePath = (value) => value.trim().replace(/^["']|["']$/g, "").replace(/^\.\//, "").replace(/^\//, "");

const parseListFields = (text) => {
  const lists = { allowedWrites: [], forbiddenWrites: [] };
  let current = null;

  for (const rawLine of text.split(/\r?\n/)) {
    const sectionMatch = rawLine.match(/^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/);
    if (sectionMatch !== null) {
      current = Object.prototype.hasOwnProperty.call(lists, sectionMatch[1])
        ? sectionMatch[1]
        : null;

      const inlineValue = sectionMatch[2].trim();
      if (current !== null && inlineValue !== "" && inlineValue !== "[]") {
        lists[current].push(inlineValue);
      }
      continue;
    }

    const itemMatch = rawLine.match(/^\s*-\s+(.+)\s*$/);
    if (current !== null && itemMatch !== null) {
      lists[current].push(itemMatch[1].trim());
      continue;
    }

    if (rawLine.trim() !== "" && !rawLine.startsWith(" ") && !rawLine.startsWith("\t")) {
      current = null;
    }
  }

  return lists;
};

const isSupportedPattern = (pattern) => {
  const withoutTrailingGlob = pattern.endsWith("/**") ? pattern.slice(0, -3) : pattern;
  return !/[?*[\]{}]/.test(withoutTrailingGlob);
};

const matchesPattern = (filePath, pattern) => {
  if (pattern.endsWith("/**")) {
    const prefix = pattern.slice(0, -3).replace(/\/+$/, "");
    return filePath === prefix || filePath.startsWith(prefix + "/");
  }

  return filePath === pattern;
};

const leaseText = readText(args[0], "lease/report file");
const changedText = readText(args[1], "changed-files file");
const parsed = parseListFields(leaseText);
const allowedWrites = parsed.allowedWrites.map(normalizePath).filter(Boolean);
const forbiddenWrites = parsed.forbiddenWrites.map(normalizePath).filter(Boolean);
const changedFiles = changedText.split(/\r?\n/).map(normalizePath).filter(Boolean);
const checks = [];
const errors = [];

for (const pattern of [...allowedWrites, ...forbiddenWrites]) {
  if (!isSupportedPattern(pattern)) {
    errors.push("manual-validation required: unsupported write pattern " + pattern);
  }
}

if (allowedWrites.length === 0) {
  errors.push("manual-validation required: no allowedWrites entries found");
}

if (errors.length === 0) {
  for (const filePath of changedFiles) {
    if (!allowedWrites.some((pattern) => matchesPattern(filePath, pattern))) {
      errors.push(filePath + " is outside allowedWrites");
      continue;
    }

    const forbiddenPattern = forbiddenWrites.find((pattern) => matchesPattern(filePath, pattern));
    if (forbiddenPattern !== undefined) {
      errors.push(filePath + " matches forbiddenWrites pattern " + forbiddenPattern);
      continue;
    }

    checks.push(filePath);
  }
}

if (errors.length > 0) {
  fail(errors);
}

print({ ok: true, helper, checks });
`;
